name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Weekly update
    - cron: '0 0 * * 0'

jobs:
  update-readme:
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL: true
          SHOW_TITLE: true
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False" 
          SHOW_PROFILE_VIEWS: "False"   
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_UPDATED_DATE: "False"
          LOCALE: en
          SYMBOL_VERSION: 1
          SECTION_NAME: waka
          COMMIT_MESSAGE: "Updated with Dev Metrics"
