name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 4 hours
    - cron: '0 0 * * 0'

jobs:
  update-readme:
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL: true
          SHOW_TITLE: true
          LOCALE: en
          SYMBOL_VERSION: 1
